name: Godot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Run GdUnit4 Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run GdUnit4 Tests
        uses: MikeSchulze/gdUnit4-action@v1.2.2
        with:
          godot-version: '4.5.1'
          paths: 'res://tests'
          timeout: 5
          retries: 3
